version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - 80:80
    networks:
      - moodle_net
  moodle:
    build: .
    depends_on:
      - db
    environment:
      - MOODLE_DB_TYPE=mysql
      - MOODLE_DB_HOST=db
      - MOODLE_DB_PORT=3306
      - MOODLE_DB_USER=${MOODLE_DB_USER}
      - MOODLE_DB_PASSWORD=${MOODLE_DB_PASSWORD}
      - MOODLE_DB_NAME=${MOODLE_DB_NAME}
    networks:
      - moodle_net
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - moodle_net

networks:
  moodle_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data:
